# Generated by Django 5.2.7 on 2025-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='full_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
